In [1]:
import pandas as pd

data = {
    'Name': ['Frank', 'Grace', 'Henry', 'Ivy', 'Jack', 'Kelly', 'Liam', 'Mia'],
    'Age': [27, 32, 39, 44, 49, 54, 59, 64],
    'City': ['San Francisco', 'Seattle', 'Miami', 'Dallas', 'Atlanta', 'Philadelphia', 'Denver', 'Phoenix'],
    'Salary': [110000, 120000, 130000, 140000, 150000, 160000, 170000, 180000]
}

df = pd.DataFrame(data)

print(df)


    Name  Age           City  Salary
0  Frank   27  San Francisco  110000
1  Grace   32        Seattle  120000
2  Henry   39          Miami  130000
3    Ivy   44         Dallas  140000
4   Jack   49        Atlanta  150000
5  Kelly   54   Philadelphia  160000
6   Liam   59         Denver  170000
7    Mia   64        Phoenix  180000


series

In [2]:
name_series = df['Name']
print("Name Series:")
print(name_series)

Name Series:
0    Frank
1    Grace
2    Henry
3      Ivy
4     Jack
5    Kelly
6     Liam
7      Mia
Name: Name, dtype: object


index

In [3]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar["y"])

7


key/value object as series

In [4]:
key_value_series = pd.Series({'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5})
print("Key/Value Objects as Series:")
print(key_value_series)

Key/Value Objects as Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64


locate row

In [5]:
row_2 = df.loc[2]
print("Row with index label 2:")
print(row_2)

Row with index label 2:
Name       Henry
Age           39
City       Miami
Salary    130000
Name: 2, dtype: object


Name index

In [8]:
# Assign a new index to the DataFrame and name it
df.index = ['d1', 'd2', 'd3', 'd4', 'd5','d6','d7','d8']
df.index.name = 'Index'

print("DataFrame with Named Indexes:")
print(df)


DataFrame with Named Indexes:
        Name  Age           City  Salary
Index                                   
d1     Frank   27  San Francisco  110000
d2     Grace   32        Seattle  120000
d3     Henry   39          Miami  130000
d4       Ivy   44         Dallas  140000
d5      Jack   49        Atlanta  150000
d6     Kelly   54   Philadelphia  160000
d7      Liam   59         Denver  170000
d8       Mia   64        Phoenix  180000


Analyzing data

In [9]:
print("First few rows:")
print(df.head())

First few rows:
        Name  Age           City  Salary
Index                                   
d1     Frank   27  San Francisco  110000
d2     Grace   32        Seattle  120000
d3     Henry   39          Miami  130000
d4       Ivy   44         Dallas  140000
d5      Jack   49        Atlanta  150000


In [10]:
print("Last few rows:")
print(df.tail())

Last few rows:
        Name  Age          City  Salary
Index                                  
d4       Ivy   44        Dallas  140000
d5      Jack   49       Atlanta  150000
d6     Kelly   54  Philadelphia  160000
d7      Liam   59        Denver  170000
d8       Mia   64       Phoenix  180000


In [11]:
print("DataFrame information:")
print(df.info())

DataFrame information:
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, d1 to d8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    8 non-null      object
 1   Age     8 non-null      int64 
 2   City    8 non-null      object
 3   Salary  8 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes
None


empty cells

In [12]:
empty_cells = df.isna().sum()
print("Empty cells:")
print(empty_cells)

Empty cells:
Name      0
Age       0
City      0
Salary    0
dtype: int64


In [17]:
# Convert 'Age' column to float (example of handling wrong data format)
df['Age'] = df['Age'].astype(float)

# Handling wrong data (for example, replacing negative salaries with NaN)
df['Salary'] = df['Salary'].apply(lambda x: x if x > 0 else None)

# Removing duplicates (if any)
df.drop_duplicates(inplace=True)
print(df)

        Name   Age           City  Salary
Index                                    
d1     Frank  27.0  San Francisco  110000
d2     Grace  32.0        Seattle  120000
d3     Henry  39.0          Miami  130000
d4       Ivy  44.0         Dallas  140000
d5      Jack  49.0        Atlanta  150000
d6     Kelly  54.0   Philadelphia  160000
d7      Liam  59.0         Denver  170000
d8       Mia  64.0        Phoenix  180000


NumPy

In [21]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Addition
print("Addition:")
print(arr1 + arr2)

# Subtraction
print("\nSubtraction:")
print(arr1 - arr2)

# Multiplication
print("\nMultiplication:")
print(arr1 * arr2)

# Division
print("\nDivision:")
print(arr1 / arr2)

result = arr1 + arr2
print("\nResult after broadcasting:")
print(result)

# Compute maximum
max_value = np.max(arr1)

# Compute minimum
min_value = np.min(arr1)

# Compute mean
mean_value = np.mean(arr1)

# Compute sum
sum_value = np.sum(arr1)

print("\nMaximum value:", max_value)
print("Minimum value:", min_value)
print("Mean:", mean_value)
print("Sum:", sum_value)


Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[ 5 12]
 [21 32]]

Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Result after broadcasting:
[[ 6  8]
 [10 12]]

Maximum value: 4
Minimum value: 1
Mean: 2.5
Sum: 10


SciPy

In [22]:
from scipy.stats import ttest_ind

# Sample data
group1 = np.array([1, 2, 3, 4, 5])
group2 = np.array([2, 3, 4, 5, 6])

# Perform t-test
t_statistic, p_value = ttest_ind(group1, group2)

print("T-statistic:", t_statistic)
print("P-value:", p_value)


T-statistic: -1.0
P-value: 0.34659350708733416


In [23]:
from scipy.stats import pearsonr

# Sample data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 5, 4, 6])

# Compute Pearson correlation coefficient
corr_coeff, p_value = pearsonr(x, y)

print("Pearson Correlation Coefficient:", corr_coeff)


Pearson Correlation Coefficient: 0.9
